// 重新导出 api-contract 类型，方便使用
export type {
  User,
  Organization,
  Apartment,
  Room,
  Tenant,
  Lease,
  Bill,
  Payment,
  UtilityReading,
  Notification,
  TokenResponse,
  LoginCredentials,
  RegisterData,
  SendSmsCodeData,
  ReportOverview,
  IncomeReport,
  OccupancyReport,
} from '@apartment-ultra/api-contract';
