/**
 * API 契约类型由 @apartment-ultra/api-contract 提供，此处统一再导出便于 @/types 引用保持不变。
 */
export {
  type SuccessBody,
  type ErrorResponseBody,
  type ErrorResponseData,
  type FieldError,
  BusinessCode,
  type PaginatedResponse,
  type User,
  type LoginCredentials,
  type RegisterData,
  type SendSmsCodeData,
  type TokenResponse,
  type MemberRole,
  type Organization,
  type MigrationStats,
  type DeletionPreview,
  type OrganizationMember,
  type OrganizationUsage,
  type SubscriptionPlan,
  type OrganizationSubscription,
  type SubscribeRequest,
  type SubscriptionStatus,
  type SubscriptionOrderStatus,
  type SubscriptionOrder,
  type SubscriptionOrderCreate,
  type Apartment,
  type RoomStats,
  type ApartmentWithStats,
  type RoomStatus,
  type Room,
  type RoomBatchCreate,
  type UtilityConfig,
  type UtilityConfigCreate,
  type UtilityConfigUpdate,
  type Tenant,
  type Lease,
  type UtilityReading,
  type BillStatus,
  type PaymentMethod,
  type Bill,
  type Payment,
  type DashboardOverview,
  type IncomeReport,
  type OccupancyReport,
  type Resource,
  type Action,
  type Permission,
  type RolePermissions,
  type UpdateRolePermissionsRequest,
  type UserPermissionsResponse,
  type SystemRole,
  type SystemRoleConfig,
} from '@apartment-ultra/api-contract';

/** 仅前端使用的 API 错误表示（openapi 风格 detail），与 client 中的 ApiError 类区分 */
export interface ApiErrorDetail {
  detail: string;
}
