"""add_room_layout_field

Revision ID: 9dcf47f1d225
Revises: 89f00294b5fd
Create Date: 2026-02-27 11:30:58.365455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dcf47f1d225'
down_revision: Union[str, None] = '89f00294b5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('layout', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'layout')
    # ### end Alembic commands ###
